
# import pandas as pd, os, zipfile, shutil
# from datetime import datetime
# from ydata_profiling import ProfileReport

# def init_folders():
#     for d in ["uploads","results","archive","extracted"]:
#         os.makedirs(d,exist_ok=True)

# def apply_theme(theme):
#     import streamlit as st
#     if theme=="Dark":
#         st.markdown("""<style>.stApp{background:#0e1117;color:white;}</style>""",unsafe_allow_html=True)

# def save_uploaded_files(files):
#     out=[]
#     for f in files:
#         p=os.path.join("uploads",f.name)
#         with open(p,"wb") as fp:
#             fp.write(f.read())
#         out.append(p)
#     return out

# def extract_zip_upload(zip_file):
#     zp=os.path.join("uploads",zip_file.name)
#     with open(zp,"wb") as f:
#         f.write(zip_file.read())
#     with zipfile.ZipFile(zp) as z:
#         z.extractall("extracted")

#     files=[]
#     for r,d,fs in os.walk("extracted"):
#         for f in fs:
#             if f.endswith((".xlsx",".xls")):
#                 files.append(os.path.join(r,f))
#     return files

# def process_excel(file_path):
#     meta=pd.read_excel(file_path,header=None,nrows=6)
#     device_id=str(meta.iloc[1,0]).split(":")[-1].strip() if len(meta)>1 else os.path.basename(file_path)

#     df=pd.read_excel(file_path,skiprows=7)

#     profile = ProfileReport(
#     df,
#     title=f"{device_id} Report",
#     explorative=True,
#     correlations={
#         "pearson": {"calculate": False},
#         "spearman": {"calculate": False},
#         "kendall": {"calculate": False},
#         "phi_k": {"calculate": False},
#         "cramers": {"calculate": False}
#     }
# )

#     ts=datetime.now().strftime("%Y%m%d_%H%M%S")
#     html=os.path.join("results",f"{device_id}_{ts}.html")

#     profile.to_file(html)

#     return {
#         "device_id":device_id,
#         "rows":len(df),
#         "html":html,
#         "status":"Success"
#     }

# def create_archive():
#     archive="archive/results_archive.zip"
#     with zipfile.ZipFile(archive,"w") as z:
#         for f in os.listdir("results"):
#             z.write(os.path.join("results",f),f)

# def clear_workspace():
#     for d in ["uploads","results","archive","extracted"]:
#         if os.path.exists(d):
#             shutil.rmtree(d)
#         os.makedirs(d)


#######################

# import pandas as pd, os, zipfile, shutil
# from datetime import datetime
# from ydata_profiling import ProfileReport

# def init_folders():
#     for d in ["uploads","results","archive","extracted"]:
#         os.makedirs(d,exist_ok=True)

# def apply_theme(theme):
#     import streamlit as st
#     if theme=="Dark":
#         st.markdown("""<style>.stApp{background:#0e1117;color:white;}</style>""",unsafe_allow_html=True)

# def save_uploaded_files(files):
#     out=[]
#     for f in files:
#         p=os.path.join("uploads",f.name)
#         with open(p,"wb") as fp:
#             fp.write(f.read())
#         out.append(p)
#     return out

# def extract_zip_upload(zip_file):
#     zp=os.path.join("uploads",zip_file.name)
#     with open(zp,"wb") as f:
#         f.write(zip_file.read())
#     with zipfile.ZipFile(zp) as z:
#         z.extractall("extracted")

#     files=[]
#     for r,d,fs in os.walk("extracted"):
#         for f in fs:
#             if f.endswith((".xlsx",".xls")):
#                 files.append(os.path.join(r,f))
#     return files

# def process_excel(file_path):
#     meta=pd.read_excel(file_path,header=None,nrows=6)
#     device_id=str(meta.iloc[1,0]).split(":")[-1].strip() if len(meta)>1 else os.path.basename(file_path)

#     df=pd.read_excel(file_path,skiprows=7)

#     profile=ProfileReport(df,title=f"{device_id} Report",explorative=True)

#     ts=datetime.now().strftime("%Y%m%d_%H%M%S")
#     html=os.path.join("results",f"{device_id}_{ts}.html")

#     profile.to_file(html)

#     with open(html, "r", encoding="utf-8") as f:
#         content = f.read()

#     content = content.replace(
#         "ydata-profiling v4.18.4",
#         "AQI Device Analytics Platform v1.0"
#     )

#     content = content.replace(
#         "Report generated by YData.",
#         "Report generated by Debabrata Doloi"
#     )

#     content = content.replace(
#         "YData",
#         "AQI Device Analytics Platform"
#     )

#     with open(html, "w", encoding="utf-8") as f:
#         f.write(content)

#     return {
#         "device_id":device_id,
#         "rows":len(df),
#         "html":html,
#         "status":"Success"
#     }

# def create_archive():
#     archive="results/archive/results_archive.zip"
#     with zipfile.ZipFile(archive,"w") as z:
#         for f in os.listdir("results"):
#             z.write(os.path.join("results",f),f)

# def clear_workspace():
#     for d in ["uploads","results","archive","extracted"]:
#         if os.path.exists(d):
#             shutil.rmtree(d)
#         os.makedirs(d)


###########################################
## Version: 3
## Date: 18/06/2026

import pandas as pd
import os
import zipfile
import shutil
import re

from datetime import datetime
from ydata_profiling import ProfileReport


def init_folders():
    for d in ["uploads", "results", "archive", "extracted"]:
        os.makedirs(d, exist_ok=True)


def apply_theme(theme):
    import streamlit as st

    if theme == "Dark":
        st.markdown(
            """
            <style>
            .stApp{
                background:#0e1117;
                color:white;
            }
            </style>
            """,
            unsafe_allow_html=True
        )


def save_uploaded_files(files):

    saved_files = []

    for f in files:

        filepath = os.path.join(
            "uploads",
            f.name
        )

        with open(filepath, "wb") as fp:
            fp.write(f.read())

        saved_files.append(filepath)

    return saved_files


def extract_zip_upload(zip_file):

    zip_path = os.path.join(
        "uploads",
        zip_file.name
    )

    with open(zip_path, "wb") as f:
        f.write(zip_file.read())

    with zipfile.ZipFile(zip_path) as z:
        z.extractall("extracted")

    excel_files = []

    for root, dirs, files in os.walk("extracted"):

        for file in files:

            if file.endswith(
                (".xlsx", ".xls")
            ):

                excel_files.append(
                    os.path.join(root, file)
                )

    return excel_files


def process_excel(file_path):

    try:

        meta = pd.read_excel(
            file_path,
            header=None,
            nrows=6
        )

        if len(meta) > 1:
            device_id = str(
                meta.iloc[1, 0]
            ).split(":")[-1].strip()
        else:
            device_id = os.path.splitext(
                os.path.basename(file_path)
            )[0]

        df = pd.read_excel(
            file_path,
            skiprows=7
        )

        df = df.dropna(
            axis=1,
            how="all"
        )

        ts = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )

        html_file = os.path.join(
            "results",
            f"{device_id}_{ts}.html"
        )

        profile = ProfileReport(
            df,
            title=f"{device_id} Report",
            explorative=False
        )

        profile.to_file(html_file)

        # ===================================
        # CUSTOMIZE HTML REPORT
        # ===================================

        with open(
            html_file,
            "r",
            encoding="utf-8"
        ) as f:
            content = f.read()

        content = content.replace(
            "Report generated by YData.",
            "Report generated by Debabrata Doloi"
        )

        content = content.replace(
            "Report generated by YData",
            "Report generated by Debabrata Doloi"
        )

        content = content.replace(
            "YData",
            "AQI Device Analytics Platform"
        )

        content = content.replace(
            "ydata-profiling",
            "AQI Device Analytics Platform"
        )

        content = re.sub(
            r'<a\s+[^>]*href="[^"]*"[^>]*>(.*?)</a>',
            r'\1',
            content,
            flags=re.DOTALL | re.IGNORECASE
        )

        with open(
            html_file,
            "w",
            encoding="utf-8"
        ) as f:
            f.write(content)

        return {
            "device_id": device_id,
            "rows": len(df),
            "html": html_file,
            "status": "Success"
        }

    except Exception as e:

        return {
            "device_id": os.path.basename(
                file_path
            ),
            "rows": 0,
            "html": "",
            "status": f"Failed: {str(e)}"
        }


def create_archive():

    archive_path = os.path.join(
        "archive",
        "results_archive.zip"
    )

    with zipfile.ZipFile(
        archive_path,
        "w",
        zipfile.ZIP_DEFLATED
    ) as z:

        for file in os.listdir("results"):

            full_path = os.path.join(
                "results",
                file
            )

            z.write(
                full_path,
                file
            )


def clear_workspace():

    for folder in [
        "uploads",
        "results",
        "archive",
        "extracted"
    ]:

        if os.path.exists(folder):
            shutil.rmtree(folder)

        os.makedirs(folder)
